/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as MyTicketsIndexRouteImport } from './routes/my-tickets/index'
import { Route as MyOrdersIndexRouteImport } from './routes/my-orders/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as MyOrdersOrderIdRouteImport } from './routes/my-orders/$orderId'
import { Route as EventsEventSlugOrIdIndexRouteImport } from './routes/events/$eventSlugOrId/index'
import { Route as DashboardScannerIndexRouteImport } from './routes/dashboard/scanner/index'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard/orders/index'
import { Route as DashboardEventsIndexRouteImport } from './routes/dashboard/events/index'
import { Route as EventsEventSlugOrIdCheckoutRouteImport } from './routes/events/$eventSlugOrId/checkout'
import { Route as DashboardEventsCreateRouteImport } from './routes/dashboard/events/create'
import { Route as DashboardEventsEventIdEditRouteImport } from './routes/dashboard/events/$eventId/edit'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTicketsIndexRoute = MyTicketsIndexRouteImport.update({
  id: '/my-tickets/',
  path: '/my-tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersIndexRoute = MyOrdersIndexRouteImport.update({
  id: '/my-orders/',
  path: '/my-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const MyOrdersOrderIdRoute = MyOrdersOrderIdRouteImport.update({
  id: '/my-orders/$orderId',
  path: '/my-orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventSlugOrIdIndexRoute =
  EventsEventSlugOrIdIndexRouteImport.update({
    id: '/events/$eventSlugOrId/',
    path: '/events/$eventSlugOrId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardScannerIndexRoute = DashboardScannerIndexRouteImport.update({
  id: '/scanner/',
  path: '/scanner/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const EventsEventSlugOrIdCheckoutRoute =
  EventsEventSlugOrIdCheckoutRouteImport.update({
    id: '/events/$eventSlugOrId/checkout',
    path: '/events/$eventSlugOrId/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardEventsCreateRoute = DashboardEventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsEventIdEditRoute =
  DashboardEventsEventIdEditRouteImport.update({
    id: '/events/$eventId/edit',
    path: '/events/$eventId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/my-orders/$orderId': typeof MyOrdersOrderIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/my-orders/': typeof MyOrdersIndexRoute
  '/my-tickets/': typeof MyTicketsIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/dashboard/events/create': typeof DashboardEventsCreateRoute
  '/events/$eventSlugOrId/checkout': typeof EventsEventSlugOrIdCheckoutRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/scanner/': typeof DashboardScannerIndexRoute
  '/events/$eventSlugOrId/': typeof EventsEventSlugOrIdIndexRoute
  '/dashboard/events/$eventId/edit': typeof DashboardEventsEventIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-orders/$orderId': typeof MyOrdersOrderIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/events': typeof EventsIndexRoute
  '/login': typeof LoginIndexRoute
  '/my-orders': typeof MyOrdersIndexRoute
  '/my-tickets': typeof MyTicketsIndexRoute
  '/register': typeof RegisterIndexRoute
  '/dashboard/events/create': typeof DashboardEventsCreateRoute
  '/events/$eventSlugOrId/checkout': typeof EventsEventSlugOrIdCheckoutRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/scanner': typeof DashboardScannerIndexRoute
  '/events/$eventSlugOrId': typeof EventsEventSlugOrIdIndexRoute
  '/dashboard/events/$eventId/edit': typeof DashboardEventsEventIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/my-orders/$orderId': typeof MyOrdersOrderIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/my-orders/': typeof MyOrdersIndexRoute
  '/my-tickets/': typeof MyTicketsIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/dashboard/events/create': typeof DashboardEventsCreateRoute
  '/events/$eventSlugOrId/checkout': typeof EventsEventSlugOrIdCheckoutRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/scanner/': typeof DashboardScannerIndexRoute
  '/events/$eventSlugOrId/': typeof EventsEventSlugOrIdIndexRoute
  '/dashboard/events/$eventId/edit': typeof DashboardEventsEventIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/my-orders/$orderId'
    | '/dashboard/'
    | '/events/'
    | '/login/'
    | '/my-orders/'
    | '/my-tickets/'
    | '/register/'
    | '/dashboard/events/create'
    | '/events/$eventSlugOrId/checkout'
    | '/dashboard/events/'
    | '/dashboard/orders/'
    | '/dashboard/scanner/'
    | '/events/$eventSlugOrId/'
    | '/dashboard/events/$eventId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-orders/$orderId'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/my-orders'
    | '/my-tickets'
    | '/register'
    | '/dashboard/events/create'
    | '/events/$eventSlugOrId/checkout'
    | '/dashboard/events'
    | '/dashboard/orders'
    | '/dashboard/scanner'
    | '/events/$eventSlugOrId'
    | '/dashboard/events/$eventId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/my-orders/$orderId'
    | '/dashboard/'
    | '/events/'
    | '/login/'
    | '/my-orders/'
    | '/my-tickets/'
    | '/register/'
    | '/dashboard/events/create'
    | '/events/$eventSlugOrId/checkout'
    | '/dashboard/events/'
    | '/dashboard/orders/'
    | '/dashboard/scanner/'
    | '/events/$eventSlugOrId/'
    | '/dashboard/events/$eventId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  MyOrdersOrderIdRoute: typeof MyOrdersOrderIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MyOrdersIndexRoute: typeof MyOrdersIndexRoute
  MyTicketsIndexRoute: typeof MyTicketsIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  EventsEventSlugOrIdCheckoutRoute: typeof EventsEventSlugOrIdCheckoutRoute
  EventsEventSlugOrIdIndexRoute: typeof EventsEventSlugOrIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tickets/': {
      id: '/my-tickets/'
      path: '/my-tickets'
      fullPath: '/my-tickets/'
      preLoaderRoute: typeof MyTicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders/': {
      id: '/my-orders/'
      path: '/my-orders'
      fullPath: '/my-orders/'
      preLoaderRoute: typeof MyOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/my-orders/$orderId': {
      id: '/my-orders/$orderId'
      path: '/my-orders/$orderId'
      fullPath: '/my-orders/$orderId'
      preLoaderRoute: typeof MyOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventSlugOrId/': {
      id: '/events/$eventSlugOrId/'
      path: '/events/$eventSlugOrId'
      fullPath: '/events/$eventSlugOrId/'
      preLoaderRoute: typeof EventsEventSlugOrIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/scanner/': {
      id: '/dashboard/scanner/'
      path: '/scanner'
      fullPath: '/dashboard/scanner/'
      preLoaderRoute: typeof DashboardScannerIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/events/$eventSlugOrId/checkout': {
      id: '/events/$eventSlugOrId/checkout'
      path: '/events/$eventSlugOrId/checkout'
      fullPath: '/events/$eventSlugOrId/checkout'
      preLoaderRoute: typeof EventsEventSlugOrIdCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/events/create': {
      id: '/dashboard/events/create'
      path: '/events/create'
      fullPath: '/dashboard/events/create'
      preLoaderRoute: typeof DashboardEventsCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/$eventId/edit': {
      id: '/dashboard/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/dashboard/events/$eventId/edit'
      preLoaderRoute: typeof DashboardEventsEventIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEventsCreateRoute: typeof DashboardEventsCreateRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardScannerIndexRoute: typeof DashboardScannerIndexRoute
  DashboardEventsEventIdEditRoute: typeof DashboardEventsEventIdEditRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEventsCreateRoute: DashboardEventsCreateRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardScannerIndexRoute: DashboardScannerIndexRoute,
  DashboardEventsEventIdEditRoute: DashboardEventsEventIdEditRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  MyOrdersOrderIdRoute: MyOrdersOrderIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MyOrdersIndexRoute: MyOrdersIndexRoute,
  MyTicketsIndexRoute: MyTicketsIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  EventsEventSlugOrIdCheckoutRoute: EventsEventSlugOrIdCheckoutRoute,
  EventsEventSlugOrIdIndexRoute: EventsEventSlugOrIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
